# Generated by Django 5.1.2 on 2024-11-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('calories_per_100g', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('total_calories', models.IntegerField(default=0)),
                ('meal_experience', models.CharField(choices=[('Happy', 'Happy'), ('Calm', 'Calm'), ('Tired', 'Tired'), ('Stressed', 'Stressed'), ('Energized', 'Energized'), ('Unhappy', 'Unhappy')], max_length=15)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='FoodServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.fooditem')),
            ],
            options={
                'verbose_name': 'Food Serving',
                'verbose_name_plural': 'Food Servings',
            },
        ),
    ]
