# Generated by Django 5.1.2 on 2024-11-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
    ]
