# Generated by Django 5.1.2 on 2024-11-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_meal_total_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food_servings',
        ),
        migrations.AddField(
            model_name='foodserving',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_servings', to='diet.meal'),
        ),
    ]
