# Generated by Django 5.1.2 on 2024-11-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start', models.DateTimeField()),
                ('sleep_end', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('quality', models.IntegerField(choices=[(1, 'very poor'), (2, 'poor'), (3, 'fair'), (4, 'good'), (5, 'very good')], default='3')),
                ('interrupted', models.BooleanField(default=False)),
            ],
        ),
    ]
