# Generated by Django 5.1.2 on 2024-11-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_alter_sleeplog_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplog',
            name='quality',
            field=models.IntegerField(choices=[(1, 'very poor'), (2, 'poor'), (3, 'fair'), (4, 'good'), (5, 'very good')], default='3'),
        ),
    ]
