# Generated by Django 5.1.2 on 2024-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_alter_sleeplog_duration_alter_sleeplog_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
