# Generated by Django 5.1.2 on 2024-11-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarylog',
            name='notes',
        ),
    ]
