# Generated by Django 5.1.2 on 2024-11-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
