# Generated by Django 5.1.2 on 2024-11-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.CharField(max_length=256, null=True)),
                ('designation', models.CharField(max_length=30)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
