# Generated by Django 5.1.2 on 2024-11-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrationlog',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
