# Generated by Django 5.1.2 on 2024-11-06 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrationlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
