# Generated by Django 5.1.2 on 2024-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assessment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
