# Generated by Django 5.1.2 on 2024-11-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
