# Generated by Django 5.1.2 on 2024-11-04 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userassessment_exercise_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
