# Generated by Django 5.1.2 on 2024-11-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userassessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extra active', 'Extra active')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='goal',
            field=models.CharField(blank=True, choices=[('Maintain', 'Maintain'), ('Loss', 'Loss'), ('Gain', 'Gain')], max_length=50, null=True),
        ),
    ]
